# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: fix_spec 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "fix_spec".freeze
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Chris Busbey".freeze]
  s.date = "2017-09-08"
  s.description = "Build and Inspect FIX Messages with RSpec and Cucumber steps".freeze
  s.email = "info@connamara.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-env",
    ".ruby-version",
    ".travis.yml",
    "CONTRIBUTION_GUIDELINES.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "QUICKFIX_LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "features/builder.feature",
    "features/equivalence.feature",
    "features/equivalence_data_dictionary.feature",
    "features/memory.feature",
    "features/message_type.feature",
    "features/nested_builder.feature",
    "features/paths.feature",
    "features/step_definitions/steps.rb",
    "features/support/FIX42.xml",
    "features/support/FIX50SP1.xml",
    "features/support/FIXT11.xml",
    "features/support/env.rb",
    "fix_spec.gemspec",
    "lib/fix_spec.rb",
    "lib/fix_spec/builder.rb",
    "lib/fix_spec/cucumber.rb",
    "lib/fix_spec/data_dictionary.rb",
    "lib/fix_spec/helpers.rb",
    "lib/fix_spec/matchers.rb",
    "lib/fix_spec/matchers/be_fix_eql.rb",
    "lib/fix_spec/matchers/have_fix_path.rb",
    "lib/fix_spec/step_definitions/fix_steps.rb",
    "lib/fix_spec/support/fix_helpers.rb",
    "spec/fix_spec/data_dictionary_spec.rb",
    "spec/fix_spec/helpers_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/connamara/fix_spec".freeze
  s.licenses = ["GPL".freeze]
  s.rubygems_version = "2.6.13".freeze
  s.summary = "Build and Inspect FIX Messages".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json_spec>.freeze, ["~> 1.1.1"])
      s.add_runtime_dependency(%q<quickfix-jruby>.freeze, [">= 1.6.4", "~> 1.6"])
      s.add_runtime_dependency(%q<cuke_mem>.freeze, ["~> 0.1.1"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 2.14"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 1.8"])
      s.add_development_dependency(%q<cucumber>.freeze, ["~> 1.3"])
      s.add_development_dependency(%q<rake>.freeze, ["~> 10.1"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
    else
      s.add_dependency(%q<json_spec>.freeze, ["~> 1.1.1"])
      s.add_dependency(%q<quickfix-jruby>.freeze, [">= 1.6.4", "~> 1.6"])
      s.add_dependency(%q<cuke_mem>.freeze, ["~> 0.1.1"])
      s.add_dependency(%q<rspec>.freeze, ["~> 2.14"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 1.8"])
      s.add_dependency(%q<cucumber>.freeze, ["~> 1.3"])
      s.add_dependency(%q<rake>.freeze, ["~> 10.1"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<json_spec>.freeze, ["~> 1.1.1"])
    s.add_dependency(%q<quickfix-jruby>.freeze, [">= 1.6.4", "~> 1.6"])
    s.add_dependency(%q<cuke_mem>.freeze, ["~> 0.1.1"])
    s.add_dependency(%q<rspec>.freeze, ["~> 2.14"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 1.8"])
    s.add_dependency(%q<cucumber>.freeze, ["~> 1.3"])
    s.add_dependency(%q<rake>.freeze, ["~> 10.1"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
  end
end

