# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fix_spec"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Busbey"]
  s.date = "2012-12-09"
  s.description = "Build and Inspect FIX Messages with spec and cucumber steps"
  s.email = "support@connamara.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "features/builder.feature",
    "features/equivalence.feature",
    "features/equivalence_data_dictionary.feature",
    "features/message_type.feature",
    "features/paths.feature",
    "features/step_definitions/steps.rb",
    "features/support/env.rb",
    "lib/fix_spec.rb",
    "lib/fix_spec/builder.rb",
    "lib/fix_spec/configuration.rb",
    "lib/fix_spec/cucumber.rb",
    "lib/fix_spec/helpers.rb",
    "lib/fix_spec/matchers.rb",
    "lib/fix_spec/matchers/be_fix_eql.rb",
    "lib/fix_spec/matchers/have_fix_path.rb",
    "spec/fix_spec/helpers_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/connamara/fix_spec"
  s.licenses = ["Connamara"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Build and Inspect FIX Messages"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json_spec>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<quickfix>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<json_spec>, ["~> 1.1.0"])
      s.add_dependency(%q<quickfix>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<bundler>, ["~> 1.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<json_spec>, ["~> 1.1.0"])
    s.add_dependency(%q<quickfix>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<bundler>, ["~> 1.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

